platform:ios, '7.0'

source 'https://github.com/CocoaPods/Specs.git'

pod 'ViewDeck', '~> 2.3.1'
pod 'SDWebImage', '~> 3.6'
pod 'ReactiveCocoa', '~> 2.3.1'
pod 'SupportKit', '~> 2.4.0'
pod 'ChameleonFramework', '~> 1.1.1'
pod 'Realm', '~> 0.89.0'
pod 'SVProgressHUD', '~> 1.1.2'
pod 'MWPhotoBrowser', '~> 1.4.1'
pod 'QuickDialog', '~> 1.0'
pod 'FXBlurView', '~> 1.6.3'
pod 'JDStatusBarNotification', '~> 1.5.0'